[package]
name = "bare"
version = "0.1.0"
edition = "2021"

# Specify a target

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO clean this up, some are unused
pcap-parser = { version = "0.14.0", features = ["data"] }
env-file-reader = "0.3.0"
etherparse = "0.13.0"
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
serde = "1.0.155"
serde_derive = "1.0.155"
serde_json = "1.0.94"
pcap = "1.0"
hex = "0.4.3"
macaddr = "1.0.1"
libc = "0.2.141"

[dependencies.pnet]
version = "0.34.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata]
authors = ["Dene Farrell dene.farrell@gmail.com"]



